services:
  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    volumes:
      - .:/sample-api
    ports:
      - "3001:3001"
    depends_on:
      - db
volumes:
  db-data:
